AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LambdaJudge

  SAM Template for LambdaJudge

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 600

Resources:
  EqualityChecker:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: checkers/
      Handler: app.equality_checker_lambda
      Role: arn:aws:iam::370358067229:role/service-role/lambdaJudgeExperiment-role-yx85ty3x
#      Layers:
#        - !Ref GCCLayer
      Runtime: python3.9
      Events:
        Check:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /check
            Method: post

  GCCLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: gcc
        Description: GCC with dependencies
        ContentUri: layers/gcc.zip
        CompatibleRuntimes:
        RetentionPolicy: Retain

  CodeRunner:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coderunners/
      Handler: app.run_code_lambda
      Role: arn:aws:iam::370358067229:role/contestant-role
      Layers:
        - !Ref GCCLayer
      Runtime: python3.9

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Check:
    Description: "API Gateway endpoint URL for Prod stage for EqualityChecker function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/check/"
  EqualityChecker:
    Description: "AWS Lambda checker for determining if the output of a code is exactly the same es the target"
    Value: !GetAtt EqualityChecker.Arn
  CodeRunner:
    Description: "AWS Lambda for executing the submitted code and getting the outputs"
    Value: !GetAtt CodeRunner.Arn
