name: Python application

on:
  push:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt]; then pip install -r requirements-dev.txt; fi
        if [ -f bouncer/requirements.txt ]; then pip install -r bouncer/requirements.txt; fi
        if [ -f coderunners/requirements.txt ]; then pip install -r coderunners/requirements.txt; fi


    - name: Test with pytest
      run: |
        pytest .
